### ISSUE TITLE
scan for viruses pipeline fails on project created from docker container scan

### ISSUE THREAD

**Issue by JonoYang** [aboutcode-org/scancode.io#1388]
There is a bug with the scan_for_viruses pipeline when run from a project created from a docker image. The error is happening here https://github.com/aboutcode-org/scancode.io/blob/main/scanpipe/pipes/clamav.py#L48 where this happens:
```
>>> Path(c.path).relative_to(project.codebase_path)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.12/pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'liferay_dxp_2024_q3_0.tar-extract/1b9b7346fee7abbc7f5538eaa23548bd05a45abe8daf6794024be0c8ad7d60bb/bin' is not in the subpath of '/var/scancodeio/workspace/projects/dxp2024q30-docker-scan-sep-18-24-155631-bfe786cc/codebase'
```

The location of a codebase resource created from a docker scan does not have the codebase path prefix.

**Comment by VarshaUN** [comment]
@JonoYang I have tried to work on it so could please test it out and suggest some improvements.Thank you
